### PR TITLE
Added stylus support with nib for vendor prefixing and rupture for me…

### PR DESCRIPTION
**Pull request by efollender**
…dia queries

### CODE REVIEW

**Comment by davezuko** [comment]
Cool, thanks! Is that firebase dependency necessary? Maybe I'm just missing something, but if it's not would you mind removing it? I'm happy to merge this in as soon as that's cleared up.

Thanks!

**Comment by efollender** [comment]
Nope, was starting another project and forgot I added that. Just removed it.

**Comment by davezuko** [comment]
Thanks, merged.

**Comment by davezuko** [comment]
Ahhhh crap, looks like I messed up a rebase and lost these changes. I'll try to fix it later this afternoon -_-

**Pull request merged**
