### PR TITLE
Simplifies how action creators are passed to the HomeView

### PR DESCRIPTION
**Pull request by davidgtonge**
I think as a starter project its a good idea to push people towards the more simple, but elegant use of the `connect` api from `react-redux`

### CODE REVIEW

**Comment by mtsr** [comment]
I like it.

Seems you forgot the CI is set up to fail on lint too.

**Comment by davezuko** [comment]
@davidgtonge if you could fix the lint errors I'll get this merged in. Also, if you wouldn't mind removing the extraneous `routerState` selection in `mapStateToProps` I'd appreciate it; kill two birds with one stone.

**Comment by davidgtonge** [comment]
@davezuko thanks have fixed the lint errors and removed the unused router state

**Comment by davezuko** [comment]
Great, thanks. Merged.

**Pull request merged**
