### PR TITLE
refactor(environments): eliminate extra dev code/markup in production

### PR DESCRIPTION
**Pull request by davezuko**

### CODE REVIEW

**Comment by davezuko** [comment]
Pinging @neverfox, @mtsr, and @nhagen since you are all fairly active contributors, I'd just like to get your opinion on this if you have a minute. It stems from https://github.com/davezuko/react-redux-starter-kit/issues/189 and a deeper issue where a lot of DevTool-related code still makes its way into production, so this is one sure-fire way of eliminating it. It's inelegant and a bit obtuse for people new to the starter kit, so I'm wondering if any of you share my wariness.

**Comment by justingreenberg** [comment]
@davezuko no prob, i will take a look this afternoon. i was playing around with babel 6 migration last night and the only issues were with the current devtools setup, so this was going to be an problem down the road either way.

i will try the same with this PR and let you know results.

another solution i was looking into was using babel transforms to inject devtools in development using https://github.com/alexkuz/react-transform-debug-inspector

will follow up later :smile:

**Comment by neverfox** [comment]
Would it not accomplish the same thing to do a conditional require of `DevTools` inside of a single `Root.js`?

**Comment by davezuko** [comment]
@neverfox that could work, but if we go that route then both the store and Root are configured at compile time rather than at runtime, since `configureStore` would have to know to never import the DevTools. I wish dead code removal would remove unused imports, would make this whole issue trivial.

**Comment by davezuko** [comment]
I'm going to close this because I think it complicates the starter kit, and anybody concerned with an as-slim-as-possible production bundle can figure this out on their own. Might offer an explanation for how to do this in https://github.com/davezuko/react-redux-starter-kit/issues/221, but I want this starter kit to be (relatively) approachable.

**Comment by nhagen** [comment]
I think that's very reasonable, though I still favor this being optimized for production out of the box. If that's how it goes, there should definitely be a section of documentation that identifies optimizations that might be useful in production environments (like this)... Though I'm not aware of any other outstanding issues like this.

**Comment by davezuko** [comment]
@nhagen I totally agree with it being optimized for production out of the box, so I'll keep playing around with solutions for this, but documentation will unfortunately have to suffice in the meantime.

**Pull request closed without merging**
