### PR TITLE
Add learning resource: tutorial on how to get started with the starter kit

### PR DESCRIPTION
**Pull request by mklinga**
This addresses the issue https://github.com/davezuko/react-redux-starter-kit/issues/722

Before merging, I would really hope to get some feedback on the post from the people who *actually* know what this stuff is all about :)

In the meantime, I have learned a lot and really appreciate this starter-kit, so thanks!

### CODE REVIEW

**Comment by mklinga** [comment]
Oh, and a direct url for the blog post: https://suspicious.website/2016/04/29/starting-out-with-react-redux-starter-kit/

**Comment by davezuko** [comment]
This is brilliant, great work.

**Comment by davezuko** [comment]
Merged, thanks again, this is awesome.

**Comment by Justinette2175** [comment]
Hello! It looks like the link to the starter kit is broken, could you let me know where I can find the resource? 

Thanks!

**Comment by mklinga** [comment]
Ah, you're right - I'll try to reupload it in the coming days. Sorry about that.

**Pull request merged**
