### PR TITLE
fix(main): specify .default property when importing RedBox using require()

### LINKED ISSUE #888: Q. Automatically finding errors that generate React `Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`
Hi Guys,

I'm really enjoying using the this starter kit as it has saved me a lot of time.

However, is it just me or is anyone else running into a large number of these types of errors:

```
warning.js:44Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js:44createElement @ ReactElementValidator.js:221renderError @ main.js:64render @ main.js:70(anonymous function) @ main.js:79__webpack_require__ @ bootstrap 84723e2…:585fn @ bootstrap 84723e2…:109(anonymous function) @ app.84723e2….js:6__webpack_require__ @ bootstrap 84723e2…:585webpackJsonpCallback @ bootstrap 84723e2…:21(anonymous function) @ app.84723e2….js:1
invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

It's literally costing me hours trying to track down where exactly I'm not exporting a function/object or some other error.

The error for all intents is basically _useless_. 

I have no idea where in the code base it's complaining about, or what its complaining about.

This is basically, "there is an error somewhere in your code, I'm not going to give you any idea where it is."

I'm sure I'm missing something, is there an option or some kind of processor I can enable that can tell me these things in advance? or in the browser? because it's very very painful process to try and find these by trial and error.

Kind regards, Jason.

### PR DESCRIPTION
**Pull request by werelax**
Fix #888

### CODE REVIEW

**Comment by davezuko** [comment]
Wow was it seriously that simple? Can't believe I missed that... Thank you so much.

**Comment by davezuko** [comment]
🙇

**Comment by werelax** [comment]
Haha no problem. But now `redbox-react` is having some trouble unmounting. I've opened a [PR to fix the issue there](https://github.com/KeywordBrain/redbox-react/pull/64).

**Comment by jnarowski** [comment]
Bravo, that's huge. Awesome work @werelax

**Comment by JMacLulich** [comment]
Just catching back up with this thread!

Wow, you mean to tell me all we had to do was to put `default` at the end and we get error messages rendered properly through hot reloading? Thanks so much @werelax this is going to save me so much of my life.

**Comment by davezuko** [comment]
@JMacLulich they should at least be a better with the new improvements in React `15.2.0` :)

**Pull request merged**
