### PR TITLE
chore(DevTools): update to stable

### PR DESCRIPTION
**Pull request by justingreenberg**
what is going on?!

### CODE REVIEW

**Comment by justingreenberg** [comment]
what is going on?!

**Comment by davezuko** [comment]
@justingreenberg I did a force push to master to clean up some old commits. Sorry :(

**Comment by justingreenberg** [comment]
lol no worries i'm gonna squash this down to one commit. it looks like there's an issue with travis anyway

**Comment by davezuko** [comment]
Ok, well thanks for the update; we can get this in once that's resolved. It looks like my force push still has this screwed up pretty badly...

_lesson learned_

**Comment by justingreenberg** [comment]
i'm going to close this... will reopen when deps are updated

**Pull request closed without merging**
