### PR TITLE
feat(webpack): added koa proxy

### PR DESCRIPTION
**Pull request by yiziz**

### CODE REVIEW

**Comment by davezuko** [comment]
Looks good, any way we could just use the `koa-proxy` npm package instead of copying it locally?

**Comment by yiziz** [comment]
@davezuko I made a change here https://github.com/davezuko/react-redux-starter-kit/pull/478/files#diff-4b90ca7d256cf3f4eedad8a25c5ff566R19 that checks `this.originalUrl` instead of `this.path`.  `this.path` is altered by the server middleware and is not an accurate representation of the path the user specified in the browser.  Since I did not see any suitable options to pass into `koa-proxy` that would solve this issue, I copied over the code and made the necessary changes.

**Comment by davezuko** [comment]
Oh wow, somehow never saw that you replied to this. Will try to get to testing this locally ASAP... launch week this week for me, so slower than normal getting to contributions.

**Comment by davezuko** [comment]
Thank you!

**Pull request merged**
