### PR TITLE
Added in hooks for chrome's redux dev tools

### PR DESCRIPTION
**Pull request by CurtisHumphrey**
see https://github.com/zalmoxisus/redux-devtools-extension for more details

### CODE REVIEW

**Comment by patrickheeney** [comment]
Related #321. Maybe the extension could be loaded in by default (e.g. removing the old dev tools) because not a lot of people expressed interest in the devtools in the viewport option.

**Comment by davezuko** [comment]
@patrickheeney I use the sidebar tools a lot and am a fan of having them be the default just so that people who spin the app up for the first time see that devtools do in fact work.

@CurtisHumphrey looks good, thank you. There's a lint error that's failing the CI build right now, so if you could fix that then we can get this merged.

**Comment by davezuko** [comment]
Closing in favor of https://github.com/davezuko/react-redux-starter-kit/pull/356, but thanks for bringing this up!

**Comment by CurtisHumphrey** [comment]
You are welcome.

**Pull request closed without merging**
