### PR TITLE
bumping react-redux

### PR DESCRIPTION
**Pull request by Nishant-Pathak**
Bumping react-redux version to 5.0.1

### CODE REVIEW

**Comment by Nishant-Pathak** [comment]
test passed in local.

**Comment by davezuko** [comment]
Yeah, it's just node-sass being finicky with yarn. Thanks for the bump, but we do also need to update the yarn.lock file; are you able to do this? If not, I can.

**Comment by davezuko** [comment]
Just saw the yarn bump, thank you; if this build fails I'll force a rebuild w/o cache to fix the node-sass issue.

**Comment by Nishant-Pathak** [comment]
@davezuko Thanks Dave, I ran this command ` yarn upgrade ` to upgrade yarn dependencies. Still it fails. Can you try that.

**Comment by davezuko** [comment]
No worries, I just merged it locally with https://github.com/davezuko/react-redux-starter-kit/commit/9506519076d61ad51ed5c26117a0581d4988a402; don't worry about CI, it's unrelated to your PR. As far as upgrading all of the other dependencies in the lock file, I'd prefer to do that at a later date.

You can see your commit has been merged here: https://github.com/davezuko/react-redux-starter-kit/commit/9506519076d61ad51ed5c26117a0581d4988a402; ignore the fact that this PR says closed and not merged, it's just due to my rebasing. Thanks again!

**Pull request closed without merging**
