### PR TITLE
Add COUNTER_DOUBLE_ASYNC action

### PR DESCRIPTION
**Pull request by dciccale**
removed

> NOTE: This is solely for demonstration purposes. In a real application,
>     you'd probably want to dispatch an action of COUNTER_DOUBLE and let the
>     reducer take care of this logic

the change is not that big, and demonstrate what the pattern should be in a real application

### CODE REVIEW

**Comment by davezuko** [comment]
Changes look good, but curious why this should be the approach vs. reusing a singular action?

**Comment by dciccale** [comment]
I think it clearly demonstrates the two actions. instead of demonstrating how to reuse code

**Comment by dciccale** [comment]
I also followed what the previous comments said:

> NOTE: This is solely for demonstration purposes. In a real application,		
  you'd probably want to dispatch an action of COUNTER_DOUBLE and let the		
  reducer take care of this logic.

And that's what is actually being done

**Comment by davezuko** [comment]
Works for me!

**Pull request merged**
