### PR TITLE
Universal / Server side rendering

### PR DESCRIPTION
**Pull request by janoist1**
Optional universal rendering. It leaves the project as it is but extends with server side rendering that can be enabled in the configuration.

### CODE REVIEW

**Comment by kuatro** [comment]
```
TypeError: __webpack_require__(...) is not a function
      at Object.<anonymous> (dist/server.js:4200:5)
      at __webpack_require__ (dist/server.js:36:30)
      at Object.<anonymous> (dist/server.js:4158:16)
      at __webpack_require__ (dist/server.js:36:30)
      at Object.defineProperty.value (dist/server.js:4133:16)
      at __webpack_require__ (dist/server.js:36:30)
      at Object.defineProperty.value (dist/server.js:4091:16)
      at __webpack_require__ (dist/server.js:36:30)
      at Object.defineProperty.value (dist/server.js:4024:20)
      at __webpack_require__ (dist/server.js:36:30)
      at _callee2$ (dist/server.js:155:25)
      at tryCatch (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (dist/server.js:336:23)
      at dist/server.js:354:15
```

**Comment by kuatro** [comment]
Without changing anything, I restarted a server, and got a new error
```
ReferenceError: _callee2 is not defined
      at _callee2 (dist/server.js:269:11)
      at dist/server.js:332:19
      at render (dist/server.js:273:20)
      at dispatch (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/koa-compose/index.js:43:32)
      at next (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/koa-compose/index.js:44:18)
      at /Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/koa-static/index.js:43:20
      at run (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/kuat/Google Drive/Projects/_learn/universal-react-redux-starter-kit/node_modules/core-js/modules/_microtask.js:18:9)
      at nextTickCallbackWith0Args (node.js:433:9)
      at process._tickDomainCallback (node.js:403:13)
```

**Comment by janoist1** [comment]
Thanks for noticing it. I forgot to publish its dependency called "simple-universal-style-loader" - which is symlinked to my copy of this starter kit... I'll sort it out tomorrow :)

**Comment by janoist1** [comment]
Done. Also, I've fixed the eslint errors.

**Comment by kuatro** [comment]
Still getting the same error even when changed `simple-universal-style-loader` to 0.14.4

**Comment by janoist1** [comment]
That is very strange ... I'm not experiencing this on my Mac but I did on my home Windows machine. I'll check it at home at keep you updated.

**Comment by janoist1** [comment]
I've just checked it on 3 machines: another Mac, a Windows and a Linux. Never seen this error again. I recommend to checkout in a new folder and start the whole thing again (npm install) ...

**Comment by rjdestigter** [comment]
It's working well for me on a linux mint machine. Tests are failing though:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Invariant Violation: _registerComponent(...): Target container is not a DOM element.
  at webpack:///~/fbjs/lib/invariant.js:45:0 <- tests/test-bundler.js:24863
```

**Comment by janoist1** [comment]
Now the tests are not failing. (merged feature/universal into master)

**Comment by kuatro** [comment]
I guess the problem was in my old NodeJS. Sorry.

**Comment by janoist1** [comment]
No probs. Let me know if anything else needs to improve or fixed.

**Comment by levivoelz** [comment]
Hi @janoist1, I'm trying this out on an older version of the starter kit, trying to convert it and am getting this error:

```
ReferenceError: window is not defined
      at Object.<anonymous> (server.js:26566:17)
      at __webpack_require__ (server.js:30:30)
      at Object.defineProperty.value (server.js:26363:18)
      at __webpack_require__ (server.js:30:30)
      at Object.defineProperty.value (server.js:22528:16)
      at __webpack_require__ (server.js:30:30)
      at Object.defineProperty.value (server.js:14856:14)
      at __webpack_require__ (server.js:30:30)
      at _callee2$ (server.js:134:25)
      at tryCatch (/Users/me/code/apps/test/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/me/code/apps/test/frontend/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/me/code/apps/test/frontend/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (server.js:313:23)
      at server.js:331:15
      at new Promise (/Users/me/code/apps/test/frontend/node_modules/core-js/modules/es6.promise.js:191:7)
      at Promise.F (server.js:542:29)
```

Any ideas? I was able to install your branch and everything went well. Just converting an old app is the issue..

Thanks!

**Comment by janoist1** [comment]
Have a look at the simple-universal-style-loader npm module.

**Comment by levivoelz** [comment]
I updated it. Still same. Will keep trying and see what I can come up with.

**Comment by levivoelz** [comment]
I was able to get it working. Had to update the way my routes were set up. Thanks @janoist1!

**Comment by janoist1** [comment]
Great! I've just realised there is another reference to the window in the src/store/createStore.js that could have been causing the issue ...

**Comment by kuatro** [comment]
Hi! I noticed that the app isn't serving routes when I set `universal = false`

**Comment by kuatro** [comment]
And how to serve the app by nginx?

**Comment by janoist1** [comment]
It is fixed now, and a new feature added: Helmet
Also, in the future please open an issue if any..: https://github.com/janoist1/universal-react-redux-starter-kit/issues

**Comment by berdof** [comment]
@janoist1 Tried to work with your fork. Currently it breaks on `npm run compile` with this error. `TypeError: Cannot read property 'src' of undefined
    at Object.<anonymous> (webpack.config.js:13:11)`

**Comment by janoist1** [comment]
Thanks, I'm already working on it. It'll be sorted in 1-2 days. Please use the issues next time: https://github.com/janoist1/universal-react-redux-starter-kit/issues

**Pull request closed without merging**
