### PR TITLE
#1207 fix(Config,Babel): Redbox error source mapping change

### PR DESCRIPTION
**Pull request by vikas0380**
RedBox showing error links to compile code instead of original code from webpack #1207

### CODE REVIEW

**Comment by vikas0380** [comment]
screen shot 2017-04-03 at 1 51 57 am

**Comment by prescottprue** [comment]
+1 for this

I was able to get the intended result without including `'transform-react-display-name'`, so that may not be needed.

**Comment by davezuko** [comment]
Really appreciate the fix, but if it's solvable without the added dependency I'd prefer that route.

Do normal source maps still work correctly with `eval`? I remember having issues in the past, but perhaps those have been fixed.

**Comment by vikas0380** [comment]
@prescottprue  Can you please provide the details, how you were able to do that. Because without adding a dependency is always a preferred solution for me.

@davezuko Very much agreed with you, without adding a dependency is always preferred by me as well. 
i haven't faced any issue  regarding eval with source maps as such. As far as Redbox is concern they recommend eval over others with webpack. https://github.com/commissure/redbox-react#sourcemaps-with-webpack

**Comment by davezuko** [comment]
So I just took a look at this with the new migration to webpack 2, and it seems like it's just an issue with Redbox. If you look at the error in the console, you see the correct component and file mapping in the stack trace. Going to dig into redbox and see about submitting a PR to them, since `source-map` (and similar) is more useful for debugging than `eval`.

**Pull request closed without merging**
