### PR TITLE
feat(compile): upgrade to webpack 2

### PR DESCRIPTION
**Pull request by mgmcdermott**
https://gist.github.com/sokra/27b24881210b56bbaff7 may be useful to check out

Having done this a few times, I thought it would be good to upgrade this popular starter kit to webpack 2 (#1057). Several things are going on here to upgrade:
- postcss and sass loader configs have moved into the webpack.LoaderOptionsPlugin (see https://github.com/postcss/postcss-loader/issues/99 for an example)
- module.preLoaders does not exist and has been replaced with the `enforce: 'pre'` option on a regular loader.
- `devtool: null` is no longer valid and has been replaced with `devtool: false`
- karma-webpack-with-fast-sourcemaps is very outdated (~60 commits behind) and does not seem to support webpack 2 so I've removed it in favor of the official karma-webpack
- upgrading of the ExtractTextPlugin is also required for webpack 2. It is only slight changes in config syntax
- `resolve.root` no longer exist and both the diff below and the gist above show the differences

I confirmed that the npm scripts still function as expected.

### CODE REVIEW

**Comment by mgmcdermott** [comment]
note that I will be editing the travis.yml to debug the travis build.

**Comment by mgmcdermott** [comment]
it appears that this does not work with cached node_modules. I will dig into what dependency is cached and causing the issues

**Comment by mgmcdermott** [comment]
It seems like the build is failing with an issue related to loader-utils
https://github.com/s-panferov/awesome-typescript-loader/issues/241

Removing the cache should solve the problem.

**Comment by mgmcdermott** [comment]
The following error keeps showing up in travis:
```
Module build failed: Error: parseQuery should get a string as first argument
    at Object.parseQuery (/home/travis/build/davezuko/react-redux-starter-kit/node_modules/loader-utils/index.js:68:9)
    at Object.module.exports (/home/travis/build/davezuko/react-redux-starter-kit/node_modules/babel-loader/index.js:80:35)
```

It seems to be an issue with loader-utils that is solved by re-installing your node_modules which resetting the cache will fix

**Comment by jonaswindey** [comment]
Any reason why you've put `dev_tool` to null?

**Comment by davezuko** [comment]
Thank you for the PR, this is definitely on my radar.

Referencing https://github.com/davezuko/react-redux-starter-kit/issues/1057 for transparency.

**Comment by mgmcdermott** [comment]
@jonaswindey, I changed the `dev_tool` from null to false due to the addition of config validation. Null is invalid. https://github.com/webpack/webpack/blob/996fdc5eebcd5a109b67efb2d53e6639d93fb264/schemas/webpackOptionsSchema.json#L632-L644

**Comment by jonaswindey** [comment]
@mgmcdermott ok, just wondering since the starter kit currently uses compiler_devtool from /config and not null

**Comment by davezuko** [comment]
Thank you for your PR, and apologies for my inattention. I'll be continuing this off of https://github.com/davezuko/react-redux-starter-kit/pull/1091 which builds on your work. Thanks!

**Pull request closed without merging**
