### PR TITLE
Fixed an issue with using cheerio when chai-enyzme and added tests to prove it

### PR DESCRIPTION
**Pull request by CurtisHumphrey**
So shallow and mount worked but finding elements my class id and render did not until this fix

### CODE REVIEW

**Comment by davezuko** [comment]
Woah, very interesting. Will pull it down when I get a minute. Thank you so much.

**Comment by davezuko** [comment]
I really wish libraries would just include the file extensions, would save so much headache.

Just tested this and it works perfectly, thanks so much for finding it and fixing it.

**Comment by davezuko** [comment]
This has been merged, ignore the close: https://github.com/davezuko/react-redux-starter-kit/commit/12676f6f20116e167725016452da01dce86f6e5e

Thanks again @CurtisHumphrey :D

**Comment by CurtisHumphrey** [comment]
You are welcome @davezuko!

**Pull request closed without merging**
