### PR TITLE
fix(fe): Use ES5 syntax instead of ES6

### PR DESCRIPTION
**Pull request by cidevant**
Dont use illegal ES6 syntax (template strings), which causes crash before start.

### CODE REVIEW

**Comment by davezuko** [comment]
I really didn't want to do this since it's a non-issue if you're on anything above `iojs ^2.0.0` (see my comment in https://github.com/davezuko/react-redux-starter-kit/pull/185) and version requirements are documented in the README, but honestly at this point it probably doesn't hurt anyone to just stick to ES5 everywhere that isn't preprocessed with Babel.

If you could update `~/webpack.config.js` to not use `const` to match these changes I'd be happy to merge this in.

**Comment by cidevant** [comment]
valid arguments, will fix it. The reason I created this pull request, coz app didn't work after clear `npm install`. Nothing is perfect in this world ;-)

**Comment by davezuko** [comment]
Ok cool, just let me know when you've made those updates and we can get it merged in.

**Comment by davezuko** [comment]
Ended up fixing this with https://github.com/davezuko/react-redux-starter-kit/pull/222

**Pull request closed without merging**
