### PR TITLE
Use redux-react-router

### PR DESCRIPTION
**Pull request by Alexandre-Herve**
Hi!
I was trying to implement redux-react-router in your awesome starter kit as an exercise (I'm discovering react and redux) and I saw it was in your roadmap: would you like to use this?

I don't know if I'm doing it right, but the router is in the state, so this might be a good start!

### CODE REVIEW

**Comment by davezuko** [comment]
Hey thanks, awesome! I'll pull it down and take a look when I get home. Does this change anything with server-side rendering?

**Comment by Alexandre-Herve** [comment]
It looks like it's just working fine!
Some potential issue though: https://github.com/acdlite/redux-react-router/issues/14

**Comment by davezuko** [comment]
Hey seems like there's an existing issue with the current server-side rendering, so I'm going to try to fix that before looking at merging this in.

**Comment by davezuko** [comment]
Hey @Alexandre-Herve, how much have you used redux-react-router? I've been doing some reading through their docs and am a bit concerned about merging this in its current state if it lacks support for things like

**Comment by davezuko** [comment]
Woops didn't mean to close this! Misclick.

**Comment by Alexandre-Herve** [comment]
So I as said I was exercising and I'm not yet familiar enough with it to ensure that everything goes smooth.

However, there don't seem to be a thousands ways of implementing this react-redux-router, so I think this is a good start point to play around like you said and see if it is worth it. I'm going to play around with it on my side too and keep you up to date with what I find.

**Comment by davezuko** [comment]
Ok sounds good. Sorry to do this to you lol but there's been quite a few changes since you originally opened the PR. If you'd be willing to resolve the merge conflicts and update the PR I'd be happy to pull it in to master.

**Comment by Alexandre-Herve** [comment]
Ok cool no prob I'll have a look!

**Comment by davezuko** [comment]
Closing this since react-router is now in `1.0.0-rc1` with fairly significant changes. I still think it would be awesome to integrate the router into Redux, so new PR's are welcome. Thanks!

**Pull request closed without merging**
