### PR TITLE
Convert classes to stateless components

### PR DESCRIPTION
**Pull request by patrickheeney**
It might be worthwhile to create a view to demonstrate a state-full component, maybe a button that toggles something.

### CODE REVIEW

**Comment by justingreenberg** [comment]
@patrickheeney have you tested this with HMR? react-transform does not currently support functional components...

**Comment by patrickheeney** [comment]
@justingreenberg It is unfortunate, but the only time I generally update stateless components is to edit the html, at which point I refresh. The modifications to the state or other parts of the app still work with HMR. How often do you edit CoreLayout or Root container? Hopefully they fix upstream soon like the babel 6 issue.

Related #277.

**Comment by justingreenberg** [comment]
@patrickheeney this breaks HMR for HomeView and other presentational components as well

**Comment by patrickheeney** [comment]
@justingreenberg Indeed, just the home view, but I would argue the others are rarely changed. However, this coincides with the existing AboutView so the current behavior of refreshing these two views would be similar.

**Comment by justingreenberg** [comment]
@patrickheeney yea I actually [added AboutView as functional component](https://github.com/davezuko/react-redux-starter-kit/commit/db66626ca8a02ecf030a3f7f5a669ac338fd5897) in my PR migrating to `redux-simple-router`, but it was really just meant to demo routing behavior

personally, i leverage HMR to maintain component state when building, styling and testing UI. this 
would break anything attached to the stateless components (styles, classes, etc)...
 
also the issue isn't babel 6, it's actually react itself—currently there is no good way to track changes to these components since they are just simple functions that render html, whereas class components are tracked using their displayName. one of the babel authors outlines the problems better than i could in gaearon/babel-plugin-react-transform#57

**Comment by patrickheeney** [comment]
I will close this now as the starter kit is likely to change by the time this is no longer an issue. Secondly I didn't update the tests. I was trying to say the issue is similar to babel 6, in that we are essentially waiting.. A "bug" in an upstream library prevents the usage of class based components with super(), and in this case a library preventing stateless components.

**Comment by justingreenberg** [comment]
another solution would be to use *pure* component classes (*only* render method) during development to support HMR development workflow, then use the babel pipeline to transform them into pure functions for production using [babel-plugin-react-pure-components](https://github.com/thejameskyle/babel-plugin-react-pure-components)

**Comment by patrickheeney** [comment]
@justingreenberg Interesting. 

Also, this worked for me as another idea. What about you?

```
class HomeViewWrapper extends React.Component {
  render () {
    return <HomeView {...this.props} />
  }
}

HomeViewWrapper.propTypes = PropTypes

export default connect(mapStateToProps, counterActions)(HomeViewWrapper)
```

**Comment by patrickheeney** [comment]
Just thinking out loud. The wrapper could be useful when developing a component, when you are done with it, comment it out for the pure component. I also like the idea of using the babel plugin for production so I might explore that as well.

**Comment by justingreenberg** [comment]
@patrickheeney yea wrapping with class is a good pattern for adding lifecycle methods and fixtures for testing (and yes would enable HMR) but this wouldn't really add much practical value over pure component classes at present. it should be noted that the react team is actively working on the referential issue and and optimizations of functional components. 

i've been using [recompose](https://github.com/acdlite/recompose) a lot lately, which is an awesome toolkit for composing pure components—when referential support is release it is going to be a game-changer!

**Comment by patrickheeney** [comment]
@justingreenberg I thought of it merely as a means to enable HMR for development. Basically you would uncomment the wrapper to dev a component, re-comment when it is "production ready". For example CoreLayout for me will never change, so I would likely always leave it a pure component. If I need to edit it where a refresh wouldn't do the job, I would wrap it for HMR. (Only temporarily until the issue is fixed).

I will have a look at recompose, sounds pretty cool.

**Comment by justingreenberg** [comment]
yeah i hear you. the problem is react-transform needs references to every upstream component to find child components. so if you wanted to enable HMR for, let's say HomeView, you would have to wrap Root and CoreLayout as well as HomeView itself. obviously this would become extremely tedious as the component tree grows...

**Comment by patrickheeney** [comment]
I didn't do any extensive testing but I only wrapped home view, the other
components were functions and HMR worked as expected. Since stateless never
change between refreshes you would have to wrap any component you want to
edit between those refreshes. If your not editing core layout for example
it should be OK. At least that is my take.

Anyway, will leave this tabled for now and see how things progress
upstream.

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Pull request closed without merging**
