### PR TITLE
Suggestion: Some cleanup

### PR DESCRIPTION
**Pull request by StevenLangbroek**
This PR has 2 things:

- a `createConstants` utility function. Should save some typing when building a large application
- change the switch statement in the reducer to use a reducers map, keeps the actual function clean :).

Would love to hear your thoughts!

### CODE REVIEW

**Comment by davezuko** [comment]
Hey, thanks for the PR, looks good!

The reducer format is definitely more a stylistic thing, but I see your version becoming more and more common so I'm complete agreement with merging it in.

The createConstants I'm a bit torn on, honestly. React comes with a `keyMirror` utility (react/lib/keyMirror) that I think does the job well enough, though you still have to do the work of assigning a null value to each property. I'm not against it to the point of not merging it in, but it would be nice to at least update the filename to `create-constants` so that it follows the naming conventions found in the rest of boilerplate. It might be nice as well to add a `utils` alias in the webpack config (`~/build/webpack/make-config`).

If you'd like to make those changes that would be awesome, and I'll gladly merge your PR. That said, there are a few lint issues (not quite sure why the build wasn't failed... I guess that's a new issue :P) that should be resolved before pulling this into master. Here's a log from the Travis build:

```
    ERROR in ./src/reducers/todos/index.js
    
    /home/travis/build/davezuko/react-redux-starter-kit/src/reducers/todos/index.js
      20:0  warning  Combine this with the previous 'const' statement         one-var
      21:3  warning  Missing space after computed key "TODO_CREATE"           key-spacing
      25:3  warning  Missing space after computed key "TODO_TOGGLE_COMPLETE"  key-spacing
      37:2  warning  Combine this with the previous 'const' statement         one-var
      39:2  warning  Expected { after 'if' condition                          curly
      39:2  error    Keyword "if" must be followed by whitespace              space-after-keywords
    
    ✖ 6 problems (1 error, 5 warnings)
    
    
    ERROR in ./src/utils/createConstants.js
    
    /home/travis/build/davezuko/react-redux-starter-kit/src/utils/createConstants.js
      3:39  error    Missing space before function parentheses    space-before-function-paren
      3:53  error    Missing space before opening brace           space-before-blocks
      6:7   warning  Missing space after computed key "constant"  key-spacing
```

The missing spaces just indicate that colons in an object should be aligned. I'll probably remove this and weaken some other rules just to make PR's easier on people, but that's for another day.

Definitely appreciate the PR, some nice improvements. Thanks so much for your help!

**Comment by StevenLangbroek** [comment]
Cool, thanks for the feedback :).

Regarding keyMirror, I investigated that initially, but didn't like the syntax. For redux purposes this small utility fits my dev style nicely.

I'll fix your points. I'm not convinced about the `one-var` rule... Most people consider it bad style (it's easy to miss a comma for example)... You?

**Comment by davezuko** [comment]
Totally see your point about conciseness, and like I said I'm totally in favor of keeping it as long as the rest of the changes are made.

I'll probably be dropping the `one-var` requirements just because it's such a controversial rule. Honestly it's just one of those things that I adopted a while ago and have stuck with ever since; it seems to fit well with enforcing manual variable hoisting and I never cared much for seeing redundant `var`'s at the top of a function :P. Your point about the commas is definitely valid, and on top of that it doesn't make much sense for a boilerplate to enforce such a debated style... so... look forward to the incoming .eslintrc update (probably tomorrow)!

Thanks again!

**Comment by StevenLangbroek** [comment]
Whoopsy! Sec, lemme fix specs.

**Comment by davezuko** [comment]
Ah looks like you may just have to provide a second argument to `createReducer` to specify what the initial state should be. Totally forgot about that.

**Pull request merged**
