### PR TITLE
feat(babel): update babel ecosystem to version 6

### PR DESCRIPTION
**Pull request by justingreenberg**
ok so i wanted to get this PR out there even though there are a couple of open issues:

### Open Issues [updated: ready to merge 12/10 :tada: ]

- [x] **fix devtools/action creators** - watch the demo video below. you will notice that the devtools are syncing correctly with the store and routing, but is is not logging the action object for `increment`

>fixed by deprecating createConstants in ce9cdee

- [x] **fix failing test** - karma is failing it's own framework test "Should have chai-as-promised helpers."

>fixed by adding runtime support in 73dfd81

**Note (5dcb43e)**: babel was not transpiling the `...rest` parameter in `createReducer`—it was causing absolute mayhem. since it does not affect usability in any way i removed it. :v: 

### PR Highlights
- **react-transform** - all transforms are working perfectly :tada: 
  - *transform-catch-errors* - intercepts errors and renders to `redbox`
  - *transform-hmr* - hmr for react components dynamically injected in hot development mode only
- **plugin support for default exports** - babel 6 [killed support for commonjs default exports](https://phabricator.babeljs.io/T2212), so we're using `babel-plugin-add-module-exports` to handle interop with es modules (more infomation in the link above)
- **eslint babel preloader** - integrated linting with webpack workflow, outputs to console on builds
- **updated webpack devtooling** - now using `cheap-module-eval-source-map`, [webpack's new recommended devtool](https://webpack.github.io/docs/configuration.html#devtool
) which enables lightning fast SourceMap generation (it will be the default in next version)

### Demo
rrsk

### CODE REVIEW

**Comment by mtsr** [comment]
I'm not sure we really need `babel-plugin-add-module-exports`, as it seems to only be necessary for CommonJS syntax. The starter kit currently only uses ES syntax, though.

**Comment by justingreenberg** [comment]
@mtsr there are a number of serious interop issues... they are well documented in this thread https://phabricator.babeljs.io/T2212.... from the author of babel, last comment in thread above:

>Killed it. I'm not willing to support this in Babel, even as an option, as it's proved to be very dangerous for refactoring and semantics. Just to be clear, this just changes the export interop. Not the import.

**Comment by davezuko** [comment]
Awesome work! I'll take a look at the `chai-as-promised` plugin, but if I can't fix it I'm not against removing it until later just so we can get Babel 6 out the door.

**Comment by davezuko** [comment]
@justingreenberg just submitted https://github.com/justingreenberg/react-redux-starter-kit/pull/1 which resolves the broken tests.

**Comment by davezuko** [comment]
Figured out the constants issue as well, it's because Babel 6 won't let you destructure default exports. Fixed here: https://github.com/justingreenberg/react-redux-starter-kit/pull/2/files

**Comment by davezuko** [comment]
Only failing on Node v4, looks like we just need to fix this: https://github.com/rackt/react-router/releases

**Comment by justingreenberg** [comment]
@davezuko is looks like [PhantomJS is having interop isssues with the babel runtime](https://travis-ci.org/davezuko/react-redux-starter-kit/jobs/96069595#L4291):

```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Error: Cannot find module "babel-runtime/helpers/interop-require"
  at /home/travis/build/davezuko/react-redux-starter-kit/karma.entry.js:11530
```

i actually tried including the runtime as well last night night, but there was the spread operator issue which was incredibly hard to pinpoint and debug. let me see if i can get the runtime up and running with a transform. give me a few mins will report back here :)

**Comment by justingreenberg** [comment]
@davezuko i fixed a few little config issues, but the error with node@4 appears to be an issue with babel 6 peerDependencies, I have to run out now but can take another a look later... 

https://travis-ci.org/davezuko/react-redux-starter-kit/jobs/96090240#L4130

since this is a starter, maybe drop support for node v4 and keep it evergreen?

**Comment by davezuko** [comment]
@justingreenberg agreed about dropping node4 (at least for now). Added a PR to your branch: https://github.com/justingreenberg/react-redux-starter-kit/pull/4

**Comment by davezuko** [comment]
:+1:

**Comment by Mistereo** [comment]
@justingreenberg any ideas why babel 6 can't handle `...rest` in createReducer?
This is strange, because it is valid es2015 code.

**Comment by justingreenberg** [comment]
@Mistereo i wish i had a good answer for you—all i can say is that was an extremely complicated transform and babel 6 is still working out the kinks. remember this isn't being executed in an es2015 runtime, each feature has to be individually transformed to es3, including module interop with commonjs

**Comment by Mistereo** [comment]
@justingreenberg just tried it and seems like everything is working on latest for me.
Both `babel-plugin-transform-es2015-spread` and `babel-plugin-transform-es2015-parameters` transforms included in `es2015` preset. So can you tell me what exactly was your issue?

**Comment by justingreenberg** [comment]
@Mistereo it must have been an issue with the way exports were being added to utility module, looks like the bug was fixed in #258—returned `...rest` param to `createReducer` in #262 :+1: thanks dude

**Comment by gaearon** [comment]
>I'm not sure we really need babel-plugin-add-module-exports, as it seems to only be necessary for CommonJS syntax. The starter kit currently only uses ES syntax, though.

Agreed. I also don't understand it was added. Yes, Babel 6 kills old broken CommonJS behavior. Why would you want to replicate it in an app? It is only useful for mixed codebases that use CommonJS with ES6, or for libraries that want to use ES6 but keep backwards compatibility with CommonJS consumers.

**Pull request merged**
