### PR TITLE
fix(eslint): only apply semicolon fix to js files

### LINKED ISSUE #276: ESLint semi-colon repair throws an error (but still works)
`npm run lint:fix` is throwing an error.  It still seems to fix the semi-colons, but I thought I should log this anyways.

```sh
⇒  npm run lint:fix   

> react-redux-starter-kit@0.18.0 lint:fix /Users/terry/Desktop/Projects/react-redux-starter-kit
> eslint **/* --fix


/Users/terry/Desktop/Projects/react-redux-starter-kit/src/index.html
  1:2  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)


npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:fix"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.18.0 lint:fix: `eslint **/* --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.18.0 lint:fix script 'eslint **/* --fix'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint **/* --fix
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.
```

### PR DESCRIPTION
**Pull request by justingreenberg**
resolves #276

### CODE REVIEW

**Comment by davezuko** [comment]
@justingreenberg does this actually work? I swear I tried this without success, but maybe I'm just losing my mind.

**Comment by justingreenberg** [comment]
don't feel bad, that happens to me all the time. it works....
eslint-fix

**Comment by davezuko** [comment]
Dammit, you're right :P.

Thanks, merging. P.S. what are you using to record gifs?

**Comment by neverfox** [comment]
I tried that and was getting not eslint-error (even for errors that aren't fixable). I'll need to take another look at this.

**Comment by davezuko** [comment]
@neverfox is actually right on this, or at least I'm getting the same results as him. Just pulled lastest and nothing happens if the `.js` is in there.

**Comment by justingreenberg** [comment]
@davezuko i just figured this out myself lol

- use regular quicktime screen recording, save to desktop
- run the .mov through [this cheesy online converter](http://image.online-convert.com/convert-to-gif) drop .gif into github and delete the files

it literally takes like 30 seconds and they end up coming out pretty crispy

**Comment by justingreenberg** [comment]
@davezuko that's weird, let me try on fresh clone

**Comment by davezuko** [comment]
@justingreenberg @neverfox just pushed https://github.com/davezuko/react-redux-starter-kit/issues/273#issuecomment-164176989 really quickly so nobody runs into this while we figure this out.

@justingreenberg thanks for the tip! Also, I just pushed a temporary fix so you'll have to just adjust that to include your `.js` extension.

**Comment by davezuko** [comment]
Also, I will eventually want to get rid of the `--quiet` flag, but the warnings about ignored files are just so obnoxious.

**Comment by justingreenberg** [comment]
both my original merge as well as the below both (using https://github.com/davezuko/react-redux-starter-kit/commit/6484f62703f93390f31beb83ca5c446d6df7939d6484f62) work for me on a fresh install  

```
// package.json...
    "lint": "eslint **/*.js",
    "lint:fix": "npm run lint -- --fix",
```

works perfectly like my screencast above. i'm not sure why it's not working for you guys :confused:

**Comment by davezuko** [comment]
Let me try reinstalling my node_modules. What's your OS?

**Comment by justingreenberg** [comment]
image

**Pull request merged**
