### PR TITLE
fix(webpack): remove public path from webpack-hot-middleware config

### PR DESCRIPTION
**Pull request by cly**

### CODE REVIEW

**Comment by developer239** [comment]
I love you. :) Seeing you commited this 3 hours ago you just gave me one good night sleep.

**Comment by patrickgordon** [comment]
Can confirm this fix also addresses issues I was having with HMR not updating

**Comment by davezuko** [comment]
Ah crap, sorry about that. Thank you for the fix!

**Comment by cly** [comment]
Sweet thanks for merging!

**Pull request merged**
