### PR TITLE
Redux devtools 0.14.0 rc1 fix

### PR DESCRIPTION
**Pull request by ptim**
A bit of gardening to silence some console warnings, in particular related to imports under 0.14.0-rc1:
https://github.com/gaearon/redux-devtools/issues/127

Temporarily install patched redux-devtools with the https://github.com/tomatau/redux-devtools fork until 0.14 is officially released)

Also adds a repo field to package.json

### CODE REVIEW

**Comment by davezuko** [comment]
Thanks, this is great and much needed. However, the Travis build is failing because it can't install dependencies over SSH. Is there a particular reason you switched the dependency type for redux-devtools? If we can get this back to an npm dependency and fix the build I'd be happy to merge this in.

Thanks!

**Comment by ptim** [comment]
ugh, sorry, premature push... I'll update this in a tick!

**Comment by ptim** [comment]
> If we can get this back to an npm dependency and fix the build I'd be happy to merge this in.

Hey David, sorry about the little mess above! The patched version I've included [tomatau/redux-devtools#e126f799bb](https://github.com/tomatau/redux-devtools/commit/e126f799bb81a61e4a2ce69fbc501e09b15b5f5d) was [rejected by @gaearon](https://github.com/gaearon/redux-devtools/issues/127) because:

>It's a tiny fix but it breaks 0.13 compatibility.

But this is not an issue for us, as we require `^0.14.0-rc1`, so we can fix the issue now! Naturally, we'd want to switch back to the official release as soon as Dan patches it.

**Comment by davezuko** [comment]
Thanks for the explanation @ptim, that makes sense to me. I'm going to open another ticket up for us to switch back to the npm version of redux-devtools when it's been appropriately updated, that way it's not forgotten. Thanks for all your work!

I merged it but I think because I rebased and reworded the first commit the auto merge tool doesn't reflect that merge. I'll have to close the PR, but it's been merged!

**Comment by ptim** [comment]
tx!

**Pull request closed without merging**
