### PR TITLE
fix(HomeView): simple spacing fix

### PR DESCRIPTION
**Pull request by justingreenberg**

### CODE REVIEW

**Comment by davezuko** [comment]
Is the benefit to replacing the `&nbsp;` just that you now get the proper separation while improving the responsiveness for smaller screens?

**Comment by justingreenberg** [comment]
@davezuko currently, the increment/incrementAsync buttons are rending without any margin, like conjoined twins... using `{' '}` is just a convention for rendering whitespace in multiline jsx :)

**Comment by davezuko** [comment]
It makes sense, I'd just never seen the convention :)

Merging shortly.

**Comment by davezuko** [comment]
Merged

**Pull request closed without merging**
